### ISSUE TITLE
[v0.8.0] MySQL DB 적재시, 에러는 없으나, encoding 문제로 깨진채로 적재되어집니다. 

### ISSUE THREAD

**Issue by J3llyBe4n** [oppenheimer-joa/movie-API#22]
## 문제 사진

<img width="336" alt="Screen Shot 2023-08-24 at 5 19 59 PM" src="https://github.com/oppenheimer-joa/movie-API/assets/23203791/cde66597-e363-47f2-9041-5ff89e00a931">

---

## CODE

```
def update_movie_location_code():
    config = configparser.ConfigParser()
    config.read('config/config.ini')
    SERVICE_KEY = config.get('KOBIS_KEYS', 'API_KEY')

    host = config.get('MYSQL', 'MYSQL_HOST')
    user = config.get('MYSQL', 'MYSQL_USER')
    password = config.get('MYSQL', 'MYSQL_PWD')
    database = config.get('MYSQL', 'MYSQL_DB')

    # MySQL 연결
    conn = mysql.connector.connect(host=host,
                                   user=user,
                                   password=password,
                                   database=database)
    cursor = conn.cursor()

    url = "http://kobis.or.kr/kobisopenapi/webservice/rest/code/searchCodeList.json"
    params = {
        "key" : SERVICE_KEY,
        "comCode" : "0105000000"
    }
    resp_data = requests.get(url=url, params=params).json()

    insert_query = "INSERT INTO movie_location (location_code, location_name) VALUES (%s, %s)"
    for data in resp_data['codes']:
        values = (data['fullCd'], data['korNm'])
        cursor.execute(insert_query, values)
        conn.commit()
    conn.close()
```

다음 함수는 외부API 로 부터 지역코드를 받아 저장하는 함수입니다. 
이때, 적재를 하는 도중 다음과 같은 형태로 적재가 되어지고 있어, encoding 문제지 않을까 조심스럽게 예측하고 있지만, 해결방안을 찾지 못하였습니다.

**Comment by woorek** [comment]
### resp_data 예시입니다.
<img width="263" alt="image" src="https://github.com/oppenheimer-joa/movie-API/assets/86358091/b5ba939d-19c7-4be7-b0d5-00c1743e0928">

### 시도 코드
```
1. values = (data['fullCd'], data['korNm'].encode('cp949')
2. values = (data['fullCd'], data['korNm'].encode('utf-8')
```

**Comment by J3llyBe4n** [comment]
--- 해결되었습니다ㅎㅎ

해당 issue 링크 타서 확인하시면 될듯합니다! 감사합니다

**Comment by J3llyBe4n** [comment]
## 해결 방안
---

DB .ini 파일에서 자체적으로 인코딩을 먼저 확인해야합니다.

<img width="745" alt="Screen Shot 2023-08-24 at 5 43 38 PM" src="https://github.com/oppenheimer-joa/movie-API/assets/23203791/a9786dc1-bd1b-4386-83be-c85503ffaf2f">

보는 것과 같이 utf8mb4로 되어있다면,

테이블 생성 및 스크립트에서 utf8mb4와 같은 형식으로 동일하게 적용하여 데이터를 적재해야합니다.

DB_conn 생성 과정

<img width="735" alt="Screen Shot 2023-08-24 at 5 44 47 PM" src="https://github.com/oppenheimer-joa/movie-API/assets/23203791/1f662ec8-af6b-45b6-aa9d-3347098ff3e8">


DB 테이블 생성 query

```
CREATE TABLE IF NOT EXISTS {테이블명} (
    ex1 VARCHAR(10) PRIMARY KEY,
    ex2 VARCHAR(255)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```
