### ISSUE TITLE
[Error] AWS DB 테이블 내용 삭제 불가

### ISSUE THREAD

**Issue by blahxblah** [oppenheimer-joa/movie-API#23]
안녕하세요. blahxblah 입니다.

TMDB FastAPI 테스트를 위해 DB 테이블의 내용을 삭제하려고 하는데 삭제가 되지 않습니다.

```bash
DELETE FROM movie;
TRUNCATE TABLE movie;

SQL Error [1205] [40001]: Lock wait timeout exceeded; try restarting transaction
```

![image](https://github.com/oppenheimer-joa/movie-API/assets/10733724/39110f88-8f02-4ba0-8210-73793207fbef)

위 사진처럼 진행이 안되고 에러가 나옵니다.

**Comment by J3llyBe4n** [comment]
해결방안 :

현재 사용중인 table에 접근시도시, 다른 곳에서 사용중이라면, lock 이 걸리게 됩니다. 

저희 API 서버 로직상 conn.close() 생활화하여, 각기다른 endPoint 끼리 문제가 발생하지 않게 소스를 수정해주시면 될 것 같습니다!
